import { Nunito_Sans } from "next/font/google";
import "./globals.css";

const noto = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Kunal S",
  description: "Generated by create Kunal S",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noto.className}>{children}</body>
    </html>
  );
}
